# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bioend',
                'doc_host': 'https://protonzilla.github.io',
                'git_url': 'https://github.com/protonzilla/bioend',
                'lib_path': 'bioend'},
  'syms': {'bioend.core': {'bioend.core.foo': ('core.html#foo', 'bioend/core.py')}}}